#!/bin/sh
NAVETC=/etc/nav
DBCONF="$NAVETC/db.conf"
NOINITDB=${NOINITDB:-0}
DB=${PGDATABASE:-nav}
USER=${PGUSER:-nav}
HOST=${PGHOST:-postgres}
PORT=${PGPORT:-5432}
PASSWORD=${PGPASSWORD:-$(pwgen 12 1)}

log()
{
    echo "$(date): $@"
}


cat > "$DBCONF" <<EOF
# autogenerated on container start
dbhost=$HOST
dbport=$PORT
db_nav=$DB
script_default=$USER
userpw_$USER=$PASSWORD
EOF

>&2 cat "$DBCONF"

if [ "${NOINITDB}" -eq 0 ]; then
   export PGHOST="$HOST"
   export PGUSER="$USER"
   export PGDATABASE="$DB"
   export PGPORT="$PORT"
   export PGPASSWORD="$PASSWORD"
fi

until psql -l; do
    log "Postgres is unavailable - sleeping"
    sleep 1
done

if [ "${NOINITDB}" -eq 0 ] && ! (psql -l | grep -q "$DB"); then
    if [ -f "/database.sql" ]; then
	log "Initializing a new database schema from /database.sql"
	navsyncdb -c -r /database.sql
    else
        log "Initializing a new database schema"
        navsyncdb -c
    fi
fi

log "Synchronizing database schema"
navsyncdb -o
log "Synchronization complete"
