#!/bin/sh
NAVETC=/usr/local/nav/etc
DBCONF="$NAVETC/db.conf"
NOINITDB=${NOINITDB:-0}
DB=${PGDATABASE:-nav}
USER=${PGUSER:-nav}
HOST=${PGHOST:-postgres}
PORT=${PGPORT:-5432}
PASSWORD=${PGPASSWORD:-$(pwgen 12 1)}

cat > "$DBCONF" <<EOF
# autogenerated on container start
dbhost=$HOST
dbport=$PORT
db_nav=$DB
script_default=$USER
userpw_$USER=$PASSWORD
EOF

>&2 cat "$DBCONF"

if [ "${NOINITDB}" -eq 0 ]; then
   export PGHOST="$HOST"
   export PGUSER="postgres"
   export PGDATABASE="$DB"
   export PGPORT="$PORT"
   export PGPASSWORD="$PASSWORD"
fi

until psql -l; do
    >&2 echo "Postgres is unavailable - sleeping"
    sleep 1
done

if [ "${NOINITDB}" -eq 0 ] && ! (psql -l | grep -q "$DB"); then
   echo "Initializing a new database schema"
   navsyncdb -c
fi

echo "Synchronizing database schema"
navsyncdb -o
